openapi: '3.0.3'
info:
  title: FCToernooi Auth
  version: '1.0'
servers:
  - url: http://localhost:3001/
paths:
  /tournaments/:
    get:
      summary: Get the tournament
      security:
        - bearerAuth: []      
      description: Get the user by id
      parameters:
      - in: path
        name: tournamentId
        schema:
          oneOf:
          - type: string
          - type: integer
        required: true
        description: Numeric ID of the tournament to get
      responses:
        '200':
          description: Created
        '400':
          description: Bad Request
    # put:
    #   summary: Update the user
    #   security:
    #     - bearerAuth: []      
    #   description: Update certain props of the user
    #   parameters:
    #     - in: path
    #       name: userId
    #       schema:
    #         type: integer
    #       required: true
    #       description: Numeric ID of the user to get
    #   requestBody:
    #     description: the user as json
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           type: object
    #           properties:
    #             emailaddress:
    #               type: string
    #   responses:
    #     '200':
    #       description: Created
    #     '422':
    #       description: Unprocessable
    # delete:
    #   summary: Removes the user
    #   security:
    #     - bearerAuth: []      
    #   description: Removes the user by id
    #   parameters:
    #   - in: path
    #     name: userId
    #     schema:
    #       type: integer
    #     required: true
    #     description: Numeric ID of the user to get
    #   responses:
    #     '200':
    #       description: Created
    #     '422':
    #       description: Unprocessable
components:
  schemas:
    RegisterAndLoginInfo:
      type: object
      properties:
        emailaddress:
          type: string
        password:
          type: string
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes  